spring.datasource.url=${DB_URL:jdbc:postgresql://postgres:5432/mediconnect}
spring.datasource.username=${DB_USERNAME:mediconnect}
spring.datasource.password=${DB_PASSWORD:mediconnect}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
